# Generated by Django 3.1.2 on 2022-05-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApp', '0002_auto_20220506_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oderTime',
            new_name='orderTime',
        ),
    ]
